### ISSUE TITLE
Optionally retry pushes

### ISSUE THREAD

**Issue by jnewland** [docker/build-push-action#84] opened 2020-07-31 18:09 UTC
Docker registries sometimes experience intermittent failures when uploading images, like the ones described in https://github.com/docker/build-push-action/issues/38. Supporting configurable retry of the push step could increase the chance of a successful build in the face of these sorts intermittent problems.

**Comment by jnewland** [comment] 2020-08-11 12:09
I've taken a first attempt at an implementation over in https://github.com/docker/github-actions/pull/23 and would be happy to mold it as desired. Thanks! 😄

**Comment by webbertakken** [comment] 2020-10-20 18:16
This would be extremely useful for our use-case in [unity-ci/docker](https://github.com/Unity-CI/docker), where we're [building](https://github.com/Unity-CI/docker/blob/main/.github/workflows/new-post-2019-2-editor-image-requested.yml#L102) unity editor images for each version and then reporting the start, publication and [failure](https://github.com/Unity-CI/docker/blob/main/.github/workflows/new-post-2019-2-editor-image-requested.yml#L160) of each build.

The problem is that when images are already published, we prevent the workflow from running and sometimes DockerHub (1 in 30 builds or so) fails during the last bit of the upload (~3GB compressed). A retry would prevent the workflow from failing in the first place.

**Comment by crazy-max** [comment] 2020-10-22 19:02
This is something that needs to be handled upstream. Chunked upload also [needs to be implemented on containerd client](https://github.com/containerd/containerd/blob/656b487d333db8ad7134d26cfe12358c46c2b7f8/remotes/docker/pusher.go#L222).

**Comment by tonistiigi** [comment] 2020-11-16 06:40
https://github.com/moby/buildkit/pull/1791

**Comment by crazy-max** [comment] 2020-12-13 05:51
@webbertakken Should be fixed through the latest buildkit stable image used by [`setup-buildx-action`](https://github.com/docker/setup-buildx-action) (moby/buildkit#1791, docker/setup-buildx-action#43).

**Closed by crazy-max** 2020-12-13 05:51 UTC
Labels: :eyes: upstream

**Comment by webbertakken** [comment] 2020-12-13 12:10
Great! Thanks for the transparent communication. Much appreciated.

**Comment by devinrsmith** [comment] 2021-12-01 18:22
Are there options that need to be setup to configure retry behavior?

**Comment by nick-at-work** [comment] 2023-01-12 17:30
I'm also unclear on how this is exposed in this action?
