### ISSUE TITLE
Issue with git clone when the repo include submodules from other repositories

### ISSUE THREAD

**Issue by or-he-MA** [docker/build-push-action#1089] opened 2024-04-04 11:55 UTC
### Description

We have some submodules in our repo, that points to some other repositories.
Since the first stage of the `build-push-action` is to checkout the current repo, it keeps failing with the error: 
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

When using the the `checkout` action (https://github.com/actions/checkout) we can overcome it using the `submodules` option, for example:
```
      - name: "Checkout current repo"
        uses: actions/checkout@v4
        with:
          submodules: recursive
```

So if i could control wether to checkout the repo and disable it, or the other hand have the option to overcome the submodules, it would be great. Since right now our workflow is failing due to that issue.

**Comment by crazy-max** [comment] 2024-04-04 11:56
Seems a duplicate of https://github.com/docker/build-push-action/issues/638

**Comment by or-he-MA** [comment] 2024-04-04 12:00
@crazy-max You are right. Didn't noticed it. The question is if there is an option to add the ability to disable the default checkout that is currently happening using the `build-push-action`.

If needed we can close this thread and i'll comment on https://github.com/docker/build-push-action/issues/638

**Comment by crazy-max** [comment] 2024-04-04 12:27
Yes you can workaround it using the [Path context](https://github.com/docker/build-push-action?tab=readme-ov-file#path-context) as shown in https://github.com/docker/build-push-action/issues/638#issuecomment-1268196131

I'm closing this issue, let's continue the convo in #638

**Closed by crazy-max** 2024-04-04 12:27 UTC
Labels: kind/duplicate
