### ISSUE TITLE
Build Push action failing with GHA cache on self-hosted runner

### ISSUE THREAD

**Issue by msdrigg** [docker/build-push-action#515] opened 2021-12-08 16:58 UTC
### Behaviour

The action fails at the caching step.

The abort message is "Github actions is temporarily unavailable", but status shows no issues with github actions. Additionally, other steps in the build process work just fine. This issue is still here after several days.

Also potentially relevant: I am using a self-hosted runner on pop-os 

The relevant logs are here:

```
#20 exporting cache
#20 preparing build cache for export
#20 preparing build cache for export 44.4s done
#20 writing layer sha256:30e1b5776710e06922c72408b2d8e6ac56f1cf66b7d97697c8c28eafe4047ba8
#20 writing layer sha256:30e1b5776710e06922c72408b2d8e6ac56f1cf66b7d97697c8c28eafe4047ba8 0.5s done
#20 writing layer sha256:371803ae1c4092d5f537dcd5d83325e87d3f137ee2b5a827a9ad4c553c6dadde
#20 writing layer sha256:371803ae1c4092d5f537dcd5d83325e87d3f137ee2b5a827a9ad4c553c6dadde 0.2s done
#20 writing layer sha256:6603222a2d2bc0adbeb6f130df205a6d879ef0e45e2a6fb1362e5549eac7f5a1
#20 writing layer sha256:6603222a2d2bc0adbeb6f130df205a6d879ef0e45e2a6fb1362e5549eac7f5a1 0.2s done
#20 writing layer sha256:6e03d496f5213fdc7b85bafc814df0743309719ffa366c78da9b33f4ab19cfe4
#20 writing layer sha256:6e03d496f5213fdc7b85bafc814df0743309719ffa366c78da9b33f4ab19cfe4 0.2s done
#20 writing layer sha256:83098237b6d3febc7584c1f16076a32ac01def85b0d220ab46b6ebb2d6e7d4d4
#20 writing layer sha256:83098237b6d3febc7584c1f16076a32ac01def85b0d220ab46b6ebb2d6e7d4d4 0.0s done
#20 writing layer sha256:88a1d963e569e91cd91639d93f6df2bdb1e64b7cd394003a5d8bb54ff231c11e
#20 writing layer sha256:88a1d963e569e91cd91639d93f6df2bdb1e64b7cd394003a5d8bb54ff231c11e 0.2s done
#20 writing layer sha256:93bbf21dbbeec1bbdb76eb6bd4ff5a2bceae29fb2b8bc287a13b8572f9c23c03
#20 writing layer sha256:93bbf21dbbeec1bbdb76eb6bd4ff5a2bceae29fb2b8bc287a13b8572f9c23c03 60.2s done
#20 ERROR: error writing layer blob: failed to parse error response 503: { 'message': 'GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.', 'ref': 'Ref A: 96CC8A3C83314F12BEA57B8D983F48B6 Ref B: ASHEDGE1321 Ref C: 2021-12-08T15:48:22Z' }: invalid character '\'' looking for beginning of object key string
------
 > exporting cache:
------
error: failed to solve: error writing layer blob: failed to parse error response 503: { 'message': 'GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.', 'ref': 'Ref A: 96CC8A3C83314F12BEA57B8D983F48B6 Ref B: ASHEDGE1321 Ref C: 2021-12-08T15:48:22Z' }: invalid character '\'' looking for beginning of object key string
Error: buildx failed with: error: failed to solve: error writing layer blob: failed to parse error response 503: { 'message': 'GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.', 'ref': 'Ref A: 96CC8A3C83314F12BEA57B8D983F48B6 Ref B: ASHEDGE1321 Ref C: 2021-12-08T15:48:22Z' }: invalid character '\'' looking for beginning of object key string
```

Is there any issue with using gha cache in build-push-action on a self-hosted runner? If so, can we add some documentation of this breakage and how to work-around it? Maybe a better error message should be added as well.

#### Steps to reproduce this issue

1. Run action with GHA cache on `ubuntu-latest`
2. Verify that the action does not fail
3. Re-run action with GHA cache on `[self-hosted, linux]`
4. Verify that the action does fail

#### Expected behaviour

Action should not fail

#### Actual behaviour

Action failed

### Configuration

* Repository URL (if public): private
* Build URL (if public): private

```yml
# action.yml
name: Test and Build
on:
  pull_request:
  push: 
    branches: [main]

jobs:
  build_and_test_and_push:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Test Build
        uses: docker/build-push-action@master
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ secrets.DOCKER_TEST_FILE }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build production image
        uses: docker/build-push-action@master
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ secrets.DOCKER_FILE }}
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

### Logs
[logs_119.zip](https://github.com/docker/build-push-action/files/7677261/logs_119.zip)

**Comment by crazy-max** [comment] 2021-12-09 10:02
@msdrigg Did you still encounter that issue? I recall that yesterday GitHub has some 503 issues with GitHub Releases. cc @thaJeztah

**Comment by msdrigg** [comment] 2021-12-09 12:31
I switched to using local cache. I realized that using a self-hosted runner would just store the files on my local fs, so I am no longer using gha cache. 

@crazy-max I do agree that warning instead of failing would be greatly preferred.

**Comment by jacobalberty** [comment] 2021-12-11 18:22
I am still getting this exact same error message having it at least warn instead of error would be a significant improvement. My builds are working just fine without the GHA cache, they just take longer. But since it's an error i get an email for every build saying it failed.

**Comment by ellisio** [comment] 2022-01-20 17:52
We randomly started getting this error this morning as well. I have submitted a ticket to GitHub support to see if there is any light they can shed on this.

**Comment by crazy-max** [comment] 2022-01-20 17:54
@ellisio I can confirm we have this issue as well:

```
#58 ERROR: failed to parse error response 503: { 'message': 'GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.', 'ref': 'Ref A: 9EAC256566594DE4B12BE39604AC0A81 Ref B: BN3EDGE0310 Ref C: 2022-01-20T16:25:26Z' }: invalid character '\'' looking for beginning of object key string
```

**Comment by philipbjorge** [comment] 2022-01-20 23:44
Thanks for throwing comments up here @ellisio and @crazy-max -- 

We were pretty stoked to have caching in place yesterday... merged to main this morning and got this error :laughing:

**Comment by ellisio** [comment] 2022-01-24 17:55
Support has escalated our issue to their engineering team. Still waiting for anything that'll help all of us. More updates as I get them.

**Comment by jacobalberty** [comment] 2022-01-24 18:09
What about getting this changed to a warning instead of a failure? That would certainly make my life easier.

**Comment by ellisio** [comment] 2022-01-24 23:28
> What about getting this changed to a warning instead of a failure? That would certainly make my life easier.

I agree, this would at least get builds passing, but if it weren't for this error we'd have never known the cache wasn't having an issue until we checked our action usage at the end of the month and seen a spike.

**Comment by jacobalberty** [comment] 2022-01-25 03:23
An option to make it a warning or a fail could be a solution. I exclusively use this in public repos right now so a spike in usage isnt an issue for me its a minor inconvenience. I have to structure my builds right now so I only run my docker build at the end so a fail doesnt take out my build pipeline and even then it makes things like pull requests require more examination on my part to determine if it failed the tests or if it just failed the cache step.

If it was an option I could just mine to not fail and just warn and things would go smoother for me. You could set yours to fail so you know to maybe delay new builds for a few days.

**Comment by ellisio** [comment] 2022-01-25 17:19
@jacobalberty I can dig that. I saw the PR, I'll give my vote. 🍻

**Comment by msdrigg** [comment] 2022-01-26 00:48
I would close this issue with a solution like that

**Comment by crazy-max** [comment] 2022-01-30 17:48
Tracked in https://github.com/moby/buildkit/issues/2578

**Closed by crazy-max** 2022-01-30 17:48 UTC
Labels: cache, buildkit

**Comment by ellisio** [comment] 2022-03-01 16:20
I know this issue is closed, but I would like to bring up that GitHub Support is claiming these are timeouts on their API. Their recommendation is to patch this [code](https://github.com/tonistiigi/go-actions-cache/blob/9642704158ff292b7016d66bd3e72ca7d98ad726/cache.go#L453) to retry on 503s, with the backoff strategy.

While that kind of patch would probably resolve this for more cases than not, it still leaves a possibility that the builds will fail. I am trying to push back and have them provide more information on _why_ these requests are timing out as, to me, that is a GitHub Infrastructure issue, not OSS issue.

**Comment by tonistiigi** [comment] 2022-03-01 16:25
> Their recommendation is to patch this [code](https://github.com/tonistiigi/go-actions-cache/blob/9642704158ff292b7016d66bd3e72ca7d98ad726/cache.go#L453) to retry on 503s, with the backoff strategy.

Where are they saying that? 503 should not be retried on the client-side. We do have retry for 429 in latest versions.

**Comment by ellisio** [comment] 2022-03-01 16:29
@tonistiigi In our support ticket. 

> GitHub commented 4 days ago
> 
> Hi Andrew,
> 
> Our engineering team would like to know if is possible for you to update your retry logic to attempt the api request again in case of timeouts and response code 503? [Here](https://github.com/tonistiigi/go-actions-cache/blob/9642704158ff292b7016d66bd3e72ca7d98ad726/cache.go#L453) is the possible code where the retry logic could be applied.
> 
> Let me know any feedback and/or questions you might have.

**Comment by krisztian-sala** [comment] 2022-06-13 07:19
I got the same issue, but with a managed runner today.

**Comment by crazy-max** [comment] 2022-06-13 08:25
@krisztian-sala Looks like an issue with GitHub, see https://github.com/actions/cache/issues/698
