### ISSUE TITLE
Fails to get layer

### ISSUE THREAD

**Issue by AndriyKalashnykov** [docker/build-push-action#79] opened 2020-07-23 21:02 UTC
When running [build-push-action ](https://github.com/AndriyKalashnykov/spring-microservices-k8s/blob/master/.github/workflows/main.yml) - specifically this [workflow run](https://github.com/AndriyKalashnykov/spring-microservices-k8s/runs/904334435?check_suite_focus=true)
on multi-stage Docker image following error occurs:

```
Step 18/22 : COPY --from=build --chown=nonroot:nonroot /tmp/target/spring-boot-loader/ ./
failed to export image: failed to create image: failed to get layer sha256:d2b5fefe683206943d83635f6efab18fba2f951b676432c3932047d3cb348381: layer does not exist
```

**Comment by lpghartz** [comment] 2020-08-06 12:30
Did you ever figure out what was going on? I'm getting the same issue -- the spring-boot-loader layer not being found, reliably, in a Azure DevOps build (which seems to use, these days, the same underlying engine as the public github infrastructure). 

Strangely, in one build definition it reliably works, and the exact same Dockerfile run in a second one doesn't, and the build output of the failed one, if downloaded and run against the Dockerfile, does work. I'm starting to think the issue is something on Microsoft's side, not in Docker or Spring's layer generation, but I haven't been able to figure out how to get any more data on it.

**Comment by AndriyKalashnykov** [comment] 2020-08-06 14:11
> Did you ever figure out what was going on? I'm getting the same issue -- the spring-boot-loader layer not being found, reliably, in a Azure DevOps build (which seems to use, these days, the same underlying engine as the public github infrastructure).
> 
> Strangely, in one build definition it reliably works, and the exact same Dockerfile run in a second one doesn't, and the build output of the failed one, if downloaded and run against the Dockerfile, does work. I'm starting to think the issue is something on Microsoft's side, not in Docker or Spring's layer generation, but I haven't been able to figure out how to get any more data on it.

Nope, didn't figure it out yet. Are there any other actions that can do similar thing?

**Comment by leordev** [comment] 2020-08-08 15:41
Same here ☹️: https://github.com/CodigoPraTodos/cursospratodos/runs/961837303 
Check the step: 🐳 Build and push Docker images

**Comment by lpghartz** [comment] 2020-08-09 17:10
So I actually figured this out. It seems to be a timing-related thing. 

Add a "RUN true" between each copy step. 

So:

COPY ...
RUN true
COPY ...
RUN true
COPY ...

etc

That fixed it reliably for me.

**Comment by crazy-max** [comment] 2020-09-02 14:03
Hi,

Can you try with the future [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92)?

**Comment by AndriyKalashnykov** [comment] 2020-09-02 15:52
> Hi,
> 
> Can you try with the future [build-push-action v2](https://github.com/docker/build-push-action/tree/v2-build-push) (#92)?

Seems to have the same error, take a look [https://github.com/AndriyKalashnykov/spring-microservices-k8s/runs/1062414050?check_suite_focus=true](https://github.com/AndriyKalashnykov/spring-microservices-k8s/runs/1062414050?check_suite_focus=true)

**Comment by crazy-max** [comment] 2020-09-02 16:27
@AndriyKalashnykov Inputs have changed in v2. See [Usage section](https://github.com/docker/build-push-action/tree/v2-build-push#usage) and also [this workflow](https://github.com/crazy-max/test-docker-action/blob/master/.github/workflows/full.yml) as an example.

**Comment by crazy-max** [comment] 2020-09-09 22:44
Version 2 has been [merged to the main branch](https://github.com/docker/build-push-action#readme) and is therefore available via `uses: docker/build-push-action@v2` (mutable tag).

As a reminder, this new version changes drastically and works with 3 new actions ([login](https://github.com/docker/login-action#readme), [setup-buildx](https://github.com/docker/setup-buildx-action#readme) and [setup-qemu](https://github.com/docker/setup-qemu-action#readme)) that we have created. Many [usage examples](https://github.com/docker/build-push-action#usage) have been added to handle most use cases.

And it should fix this current issue. Don't hesitate if you have any questions.

**Closed by crazy-max** 2020-09-09 22:44 UTC
