### ISSUE TITLE
Inconsistent dockerignore behavior from other builders

### ISSUE THREAD

**Issue by syntaqx** [docker/build-push-action#182] opened 2020-10-18 15:47 UTC
> ⚠️ I'm not entirely sure if this is an issue with GitHub Actions, or this action specifically, but I didn't know where else to report it so figured this would be a good start. It's also quite possible that I'm an idiot and I'm doing something wrong that hopefully will be obvious to someone else, but I'm running into a wall with this, so here goes nothing: __#insecurities__

### Behaviour

It appears to me that the `.dockerignore` is being completely ignored when building using this action, which is an obvious inconsistency from other build[x] build environments (I've tested using my local Windows environment, remote ubuntu VM's, other CI tooling) just to be sure.

#### Steps to reproduce this issue

I used a whitelist-style [`.dockerignore`](https://github.com/syntaqx/api/blob/fd5e4b3c616ec3033a391734993abb92592d2403/.dockerignore) to remove any rule parsing inconsistencies that I could, trying to keep it simple:

```
*
*/

# do not ignore source files and assets - whitelist
!assets/
!cmd/
!internal/
!pkg/
!static/
!tools/

# do not ignore go module files
!go.mod
!go.sum
```

#### Expected behaviour

We should respect `.dockerignore` - He's tryin his best.

#### Actual behaviour

The [run output](https://github.com/syntaqx/api/runs/1271439413#step:10:115) shows a lot of files that aren't whitelisted, highlighted as `-` diffs. I do not see these files in other build environments using either `docker build` or `docker buildx build`

```diff
#11 [builder 6/8] COPY . .
#11 DONE 0.1s
#12 [builder 7/8] RUN ls -alh
#12 0.082 total 108K   
#12 0.083 drwxr-xr-x    1 root     root        4.0K Oct 18 15:18 .
#12 0.083 drwxrwxrwx    1 root     root        4.0K Oct 18 15:17 ..
- #12 0.083 -rw-rw-rw-    1 root     root         156 Oct 18 15:17 .dockerignore
- #12 0.083 -rw-rw-rw-    1 root     root         682 Oct 18 15:17 .editorconfig
- #12 0.083 -rw-rw-rw-    1 root     root          68 Oct 18 15:17 .envrc
- #12 0.083 -rw-rw-rw-    1 root     root        1.3K Oct 18 15:17 .gitattributes
- #12 0.083 drwxrwxrwx    3 root     root        4.0K Oct 18 15:17 .github
- #12 0.083 -rw-rw-rw-    1 root     root         468 Oct 18 15:17 .gitignore
- #12 0.083 -rw-rw-rw-    1 root     root         339 Oct 18 15:17 .pre-commit-config.yaml
- #12 0.083 drwxrwxrwx    2 root     root        4.0K Oct 18 15:17 .vscode
- #12 0.083 -rw-rw-rw-    1 root     root         930 Oct 18 15:17 Dockerfile
- #12 0.083 -rw-rw-rw-    1 root     root        1.1K Oct 18 15:17 LICENSE
- #12 0.083 -rw-rw-rw-    1 root     root         131 Oct 18 15:17 README.md
- #12 0.083 -rw-rw-rw-    1 root     root          12 Oct 18 15:17 api.go
#12 0.083 drwxrwxrwx    2 root     root        4.0K Oct 18 15:17 assets
#12 0.083 drwxrwxrwx    3 root     root        4.0K Oct 18 15:17 cmd
- #12 0.084 -rw-rw-rw-    1 root     root         794 Oct 18 15:17 docker-compose.yml
#12 0.084 -rw-rw-rw-    1 root     root         238 Oct 18 15:17 go.mod
#12 0.084 -rw-rw-rw-    1 root     root       11.0K Oct 18 15:17 go.sum
- #12 0.084 -rw-rw-rw-    1 root     root          37 Oct 18 15:17 heroku.yml
#12 0.084 drwxrwxrwx    3 root     root        4.0K Oct 18 15:17 internal
#12 0.084 drwxrwxrwx    3 root     root        4.0K Oct 18 15:17 pkg
#12 0.084 drwxrwxrwx    2 root     root        4.0K Oct 18 15:17 static
#12 0.084 drwxrwxrwx    2 root     root        4.0K Oct 18 15:17 tools
#12 DONE 0.1s
```

### Configuration

* Repository URL (if public): https://github.com/syntaqx/api
* Build URL (if public): https://github.com/syntaqx/api/runs/1271439413#step:10:115

```yml
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out source
        uses: actions/checkout@v2
      -
        name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      -
        name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE="${DOCKER_IMAGE:-$GITHUB_REPOSITORY}"
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo "${GITHUB_REF#refs/heads/}" | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          if [ "$GITHUB_EVENT_NAME" != "pull_request" ]; then
            TAGS="${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=image::"${DOCKER_IMAGE}"
          echo ::set-output name=version::"${VERSION}"
          echo ::set-output name=tags::"${TAGS}"
          echo ::set-output name=created::"$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      -
        name: Build values
        run: |
          echo Version: ${{ steps.prep.outputs.version }}
          echo Docker Image: ${{ steps.prep.outputs.image }}
          echo Docker Tags: ${{ steps.prep.outputs.tags }}
          echo Created: ${{ steps.prep.outputs.created }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |-
            version=${{ steps.prep.outputs.version }}
            vcs_ref=${{ github.ref }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          labels: |
            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

### Logs

[logs_27.zip](https://github.com/docker/build-push-action/files/5397743/logs_27.zip)

## Please save me 😢

**Comment by sagikazarmark** [comment] 2020-10-19 19:56
This is a wild guess, but I think it's because you use [git context](https://github.com/docker/build-push-action#git-context) which is the default.

Try using [path context](https://github.com/docker/build-push-action#path-context)

**Comment by crazy-max** [comment] 2020-10-19 21:16
@syntaqx I was able to [reproduce your issue](https://github.com/crazy-max/test-docker-action/actions/runs/316337339) and it looks like it only affects the git context. Can you open an issue on the [buildkit repo](https://github.com/moby/buildkit) please? Thanks.

**Comment by syntaqx** [comment] 2020-10-20 06:45
What would you like me to convey in the new issue? Just the same information here?

Also, I'm not totally sure if I understand the path context workaround.. do I just add `context: .` to the build `with`?

**Comment by crazy-max** [comment] 2020-10-20 20:56
@syntaqx 

> What would you like me to convey in the new issue? Just the same information here?

It's an upstream issue so yes you can provide the same info on buildkit repo.

> Also, I'm not totally sure if I understand the path context workaround.. do I just add context: . to the build with?

Yes, `context: .` will be enough in your case.

**Comment by tonistiigi** [comment] 2020-10-21 01:10
Dockerignore only applies to transferring local files to the build daemon and not when building from git or remote tarball. This is consistent with how `docker build` has always worked.

**Comment by crazy-max** [comment] 2020-10-22 17:25
Yeah @tonistiigi is right, this is the expected beahvior.

**Closed by crazy-max** 2020-10-22 17:25 UTC
Labels: :eyes: upstream

**Comment by mrmachine** [comment] 2021-04-07 04:24
@tonistiigi @crazy-max It might be expected, but it is very confusing for someone coming from local build or other CI environments that by default respect `.dockerignore`.

After re-reading the usage section of the README just now (https://github.com/docker/build-push-action#usage) I feel like this caveat should be clearly explained there, alongside the limitation that prior "file mutation steps" will be ignored.

Even the docker build docs, which talk about using a git repository as context and in the same document talk about using `.dockerignore` to avoid sending files to the context, do not mention the fact that `.dockerignore` is completely ignored with a git context.

- https://docs.docker.com/engine/reference/commandline/build/#git-repositories
- https://docs.docker.com/engine/reference/commandline/build/#use-a-dockerignore-file

**Comment by dvalentiate** [comment] 2021-07-13 18:45
I've created a [PR](https://github.com/docker/build-push-action/pull/408/files) to detail that .dockerignore is ignored.
