### ISSUE TITLE
Add retry on build and push action. 

### ISSUE THREAD

**Issue by simlarsen** [docker/build-push-action#974] opened 2023-09-27 16:37 UTC
### Description

Some jobs like this https://github.com/OneUptime/oneuptime/actions/runs/6328460825/job/17186766895 are failing on buiild because of network issues with gIthub runner. 

Please add a retry param to action step, so if the build fails it retries again.

**Comment by crazy-max** [comment] 2023-11-10 14:42
Closing as it seems a duplicate of https://github.com/docker/build-push-action/issues/719

**Closed by crazy-max** 2023-11-10 14:42 UTC
Labels: kind/enhancement, status/triage
